### ISSUE TITLE
Issues with conda envs for multi-BLAS testing

### ISSUE THREAD

**Issue by rgommers** [rgommers/meson#1]
@h-vetinari here are the initial issues I ran into:

(1) The script wants `click` in the `base` env, but that's not installable since it depends on a recent `setuptools` and upgrading is not allowed because `conda` depends on `setuptools` too. Both with conda and mamba, trying to install `click` ends with:
```
RemoveError: 'setuptools' is a dependency of conda and cannot be removed from
conda's operating environment.
```

(2) I then tried to use the script from my scipy-dev env, where I already had `click`. Running `blas blas.sh spinup --env=linux_netlib_pthreads` ends with:
```
CondaValueError: invalid package specification: libblas=*=*netlib blas-devel=3.9.0=5*
```

(3) Running `blas blas.sh spinup --env=linux_blis_pthreads` works, however it does an editable install of `meson` in the base env because this line is run from `_blas.py` without activating the correct env first:
```
subprocess.call([f"{base_bindir}/pip", "install", "-e", "."])
```
This can't really work as structured I think, and also `pip` should be installed in the test env in order to not get confusing bugs. Mixing tools from two different envs can't really work with conda I believe.

(4) Then, the tests don't actually run from the scipy-dev env in which `click` is installed, as are the `meson` editable install and `ninja`:
```
$ which meson
/home/rgommers/mambaforge/envs/scipy-dev/bin/meson
$ which ninja
/home/rgommers/mambaforge/envs/scipy-dev/bin/ninja
$ ninja --version
1.11.1

$ bash blas.sh test linux_blis_pthreads
Running tests in linux_blis_pthreads
WARNING: Found ninja <1.9, tests will run slower
Traceback (most recent call last):
  File "/home/rgommers/code/meson/run_unittests.py", line 38, in <module>
    from unittests.allplatformstests import AllPlatformTests
  File "/home/rgommers/code/meson/unittests/allplatformstests.py", line 65, in <module>
    from run_tests import (
  File "/home/rgommers/code/meson/run_tests.py", line 70, in <module>
    raise RuntimeError('Could not find Ninja v1.7 or newer')
RuntimeError: Could not find Ninja v1.7 or newer
```
This is likely to be because after environment activation, some random `ninja` gets picked up, there is no good way I believe to use it from a random env.

(5) Minor CLI usability issues: the `linux_` can be dropped from the env names to make things less verbose, and using `"\n".join` in the `list` command makes the output more readable.

### To discuss

The most important thing is how the test envs are structured I think. I don't quite understand the idea here, with the BLAS libraries installed in an env that is different from the one that the tests are run from and `pip`/`meson`/`ninja` are installed in.

**Comment by h-vetinari** [comment]
Thanks for testing & the write-up, I'll look at it ASAP.

> The most important thing is how the test envs are structured I think. I don't quite understand the idea here, with the BLAS libraries installed in an env that is different from the one that the tests are run from and `pip`/`meson`/`ninja` are installed in.

The idea was to have meson installed (from its in-development state) in each of the BLAS envs separately. We can of course add pip & ninja in those environments.

**Comment by rgommers** [comment]
> The idea was to have meson installed (from its in-development state) in each of the BLAS envs separately. We can of course add pip & ninja in those environments.

Great, that sounds right to me. To install and run `meson`, the test env of course will need `python` too. It seems like we'd want a fully functional `meson-dev` env + the extras for BLAS testing on top.

**Comment by h-vetinari** [comment]
Alright, sorry for the delay, back from travelling and should now have hopefully tackled all the points you raised.

In particular:
> (1) The script wants click in the base env

Rewritten with argparse, with the added benefit that the interface got much more regular

> (2) Running `blas blas.sh spinup --env=linux_netlib_pthreads` ends with: [error]

Fixed

> (3) Running `blas blas.sh spinup --env=linux_blis_pthreads` works, however it does an editable install of `meson` in the base env because this line is run from `_blas.py` without activating the correct env first

This was an oversight that needed a more involved-than-expected fix: Due to the way we cannot do activation from python, I had to create a new subcommand that installs meson into a given environment (or all)

> (4) Then, the tests don't actually run from the scipy-dev env in which `click` is installed, as are the `meson` editable install and `ninja`:

I've now added `pip` and `ninja` to the base specs of every environment. Can easily be extended of course.

> (5) Minor CLI usability issues: the linux_ can be dropped from the env names to make things less verbose, and using "\n".join in the list command makes the output more readable.

I've done the former, but not the latter (as it's mainly an internal tool necessary to set up the loop on the bash side; I can try to think if this can be changed).

I also need to double-check if `_has_meson` part works correctly, but installing meson in my WSL is so glacially slow that I've run out of time tonight. Hopefully this should be a step forward though!

**Comment by h-vetinari** [comment]
> I also need to double-check if `_has_meson` part works correctly, but installing meson in my WSL is so glacially slow that I've run out of time tonight. Hopefully this should be a step forward though!

This needed another fix, but should work correctly now.
